[package]
name = "jira_cli"
version = "0.0.1"
edition = "2021"
rust-version = "1.59"
authors = ["sycured <60801403+sycured@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true

[profile.dev]
opt-level = 3
lto = true

[dependencies]
base64 = "0.13.0"
clap = {version="3.1.6", features=["cargo", "env", "wrap_help"]}
dialoguer = "0.10.0"
serde_json = "1.0.79"
ureq = {version="2.4.0", features=["default", "json", "native-certs"]}
